services:
  web-app:
    build:
        context: .
    ports:
      - "8080:8080"
    volumes:
        - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
        context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
        - ./service:/service
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  flower:
    build:
        context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
        - ./service:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
        - "5555:5555"