# Generated by Django 3.2.16 on 2023-04-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='discount_percent',
            new_name='price',
        ),
    ]
